<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AS_FBX-reader</AssemblyName>
    <RootNamespace>AS.FBXReader</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.5" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
  </ItemGroup>
</Project>
